name: easy_loading
description: Flutter plugin for loading more listview and grid view.
version: 0.0.3
author: phuongphally@gmail.com
homepage: https://github.com/phuongphally/easy_loading

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

